import Script from 'next/script'

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <Script
          src={`https://maps.googleapis.com/maps/api/js?key=AIzaSyAxuq9_dntm1P2OM3NArO2xhu9HA-zsPqQ&libraries=places`}
          strategy="afterInteractive"
        />
      </head>
      <body>{children}</body>
    </html>
  )
}


